In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Social_Network_Ads.csv")
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [4]:
data.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [5]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

data['Gender'] = LabelEncoder().fit_transform(data['Gender'])
data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [9]:
# Drop user ID as it is unique for each user
data.drop(["User ID"], axis=1, inplace=True)
data

     Gender  Age  EstimatedSalary  Purchased
0         0   19            19000          0
1         0   35            20000          0
2         1   26            43000          0
3         1   27            57000          0
4         0   19            76000          0
..      ...  ...              ...        ...
395       1   46            41000          1
396       0   51            23000          1
397       1   50            20000          1
398       0   36            33000          0
399       1   49            36000          1

[400 rows x 4 columns]

In [10]:
# def min_max_normalize( feature ):
#     df[ feature ] = ( df[feature] - df[feature].min() ) / ( df[feature].max() - df[feature].min() ) 

# min_max_normalize("EstimatedSalary")
# min_max_normalize("Age")

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
data[['EstimatedSalary', 'Age']] = scaler.fit_transform(data[['EstimatedSalary', 'Age']])

In [11]:
data

     Gender       Age  EstimatedSalary  Purchased
0         0  0.023810         0.029630          0
1         0  0.404762         0.037037          0
2         1  0.190476         0.207407          0
3         1  0.214286         0.311111          0
4         0  0.023810         0.451852          0
..      ...       ...              ...        ...
395       1  0.666667         0.192593          1
396       0  0.785714         0.059259          1
397       1  0.761905         0.037037          1
398       0  0.428571         0.133333          0
399       1  0.738095         0.155556          1

[400 rows x 4 columns]

In [13]:
from sklearn.model_selection import train_test_split

X = np.asarray(data.drop(["Purchased"], axis=1))
y = np.asarray(data["Purchased"])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [15]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [18]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8416666666666667

In [31]:
from sklearn.metrics import confusion_matrix, classification_report

matrix = confusion_matrix(y_test, y_pred)

print(matrix)
print(classification_report(y_test, y_pred))

[[80  3]
 [16 21]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89        83
           1       0.88      0.57      0.69        37

    accuracy                           0.84       120
   macro avg       0.85      0.77      0.79       120
weighted avg       0.85      0.84      0.83       120

In [32]:
tp = ((y_pred == 0) & (y_test == 0)).sum()
fp = ((y_pred == 0) & (y_test == 1)).sum()
tn = ((y_pred == 1) & (y_test == 1)).sum()
fn = ((y_pred == 1) & (y_test == 0)).sum()

recall = tp/(tp + fn)
accuracy = (tp + tn)/(tp + fp + tn + fn)
precision = tp / (tp + fp)
error = 1 - accuracy
f1 = (2 * recall * precision)/(recall + precision)

print("Recall: ", recall)
print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)

Recall:  0.963855421686747
Precision:  0.8333333333333334
Accuracy:  0.8416666666666667
F1 Score:  0.8938547486033519

In [29]:
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[80,  3],
       [16, 21]])